Revert kembali configure.in

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -694,6 +694,13 @@ XMLTO
 HAVE_DOT
 DOT
 DOTDIR
+GETCONF
+NUM_CPUS
+PROC_MULTIPLY
+NUM_PROCS
+GLIBC_VER
+LIBSTDCPP_VER
+GCC3DEP
 SET_MAKE
 INSTALL_PROGRAM
 INSTALL_SCRIPT
@@ -1309,6 +1316,10 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-cpus             The number of cpus to be used for building(see --with-procs, default 1)
+  --with-getconf          Enable automagical buildtime configuration
+  --with-proc-multiply    Multiply this * number of cpus for parallel making(default 2).
+  --with-procs            The number of processes to run in parallel during make(num_cpus * multiplier).
   --with-gnu-ld           assume the C compiler uses GNU ld default=no
   --with-libiconv-prefix[=DIR]  search for libiconv in DIR/include and DIR/lib
   --without-libiconv-prefix     don't search for libiconv in includedir and libdir
@@ -1785,7 +1796,7 @@ ac_config_headers="$ac_config_headers include/config.h:buildlib/config.h.in incl
 
 
 cat >>confdefs.h <<_ACEOF
-#define VERSION "0.7.6ubuntu14-0blankon3"
+#define VERSION "0.7.6ubuntu14"
 _ACEOF
 
 PACKAGE="apt"
@@ -7018,10 +7029,280 @@ DOTDIR=$(dirname $DOT)
 
 
 
-ah_NUM_PROCS
-rc_GLIBC_VER
-rc_LIBSTDCPP_VER
-ah_GCC3DEP
+
+# Check whether --with-getconf was given.
+if test "${with_getconf+set}" = set; then
+  withval=$with_getconf; if test "$withval" = "yes"; then
+			# Extract the first word of "getconf", so it can be a program name with args.
+set dummy getconf; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_GETCONF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GETCONF in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GETCONF="$GETCONF" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GETCONF="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+GETCONF=$ac_cv_path_GETCONF
+if test -n "$GETCONF"; then
+  { echo "$as_me:$LINENO: result: $GETCONF" >&5
+echo "${ECHO_T}$GETCONF" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+		elif test ! "$withval" = "no";then
+			{ echo "$as_me:$LINENO: checking getconf" >&5
+echo $ECHO_N "checking getconf... $ECHO_C" >&6; }
+			{ echo "$as_me:$LINENO: result: $withval" >&5
+echo "${ECHO_T}$withval" >&6; }
+			GETCONF=$withval
+		fi
+else
+  # Extract the first word of "getconf", so it can be a program name with args.
+set dummy getconf; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_path_GETCONF+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $GETCONF in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_GETCONF="$GETCONF" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_path_GETCONF="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  ;;
+esac
+fi
+GETCONF=$ac_cv_path_GETCONF
+if test -n "$GETCONF"; then
+  { echo "$as_me:$LINENO: result: $GETCONF" >&5
+echo "${ECHO_T}$GETCONF" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+
+fi
+
+
+
+{ echo "$as_me:$LINENO: checking number of cpus" >&5
+echo $ECHO_N "checking number of cpus... $ECHO_C" >&6; }
+
+# Check whether --with-cpus was given.
+if test "${with_cpus+set}" = set; then
+  withval=$with_cpus;
+		if test "$withval" = "yes"; then
+
+	if test ! -z "$GETCONF";then
+		old_args="$@"
+		set -- SC_NPROCESSORS_ONLN _NPROCESSORS_ONLN
+		while eval test -z \"\$NUM_CPUS\" -a ! -z \"$1\";do
+			eval NUM_CPUS=`$GETCONF "$1" 2>/dev/null`
+			shift
+		done
+	fi
+	if eval test -z \"\$NUM_CPUS\" -o \"\$NUM_CPUS\" = "-1";then
+		eval NUM_CPUS="1"
+	fi
+
+		elif test ! "$withval" = "no";then
+			NUM_CPUS=$withval
+		elif test "$withval" = "no";then
+			NUM_CPUS=1
+		fi
+else
+
+	if test ! -z "$GETCONF";then
+		old_args="$@"
+		set -- SC_NPROCESSORS_ONLN _NPROCESSORS_ONLN
+		while eval test -z \"\$NUM_CPUS\" -a ! -z \"$1\";do
+			eval NUM_CPUS=`$GETCONF "$1" 2>/dev/null`
+			shift
+		done
+	fi
+	if eval test -z \"\$NUM_CPUS\" -o \"\$NUM_CPUS\" = "-1";then
+		eval NUM_CPUS="1"
+	fi
+
+
+fi
+
+	ah_NUM_CPUS_msg="$NUM_CPUS"
+	if test "$NUM_CPUS" = "0"; then
+		# broken getconf, time to bitch.
+		ah_NUM_CPUS_msg="found 0 cpus.  Has someone done a lobotomy?"
+		NUM_CPUS=1
+	fi
+	if test $NUM_CPUS = 1 ;then
+		default_PROC_MULTIPLY=1
+	else
+		default_PROC_MULTIPLY=2
+	fi
+	{ echo "$as_me:$LINENO: result: $ah_NUM_CPUS_msg" >&5
+echo "${ECHO_T}$ah_NUM_CPUS_msg" >&6; }
+
+
+
+	{ echo "$as_me:$LINENO: checking processor multiplier" >&5
+echo $ECHO_N "checking processor multiplier... $ECHO_C" >&6; }
+
+# Check whether --with-proc-multiply was given.
+if test "${with_proc_multiply+set}" = set; then
+  withval=$with_proc_multiply; if test "$withval" = "yes"; then
+			PROC_MULTIPLY=$default_PROC_MULTIPLY
+		elif test ! "$withval" = "no";then
+			PROC_MULTIPLY=$withval
+		fi
+else
+  PROC_MULTIPLY=$default_PROC_MULTIPLY
+
+fi
+
+	{ echo "$as_me:$LINENO: result: $PROC_MULTIPLY" >&5
+echo "${ECHO_T}$PROC_MULTIPLY" >&6; }
+
+
+
+
+	{ echo "$as_me:$LINENO: checking number of processes to run during make" >&5
+echo $ECHO_N "checking number of processes to run during make... $ECHO_C" >&6; }
+
+# Check whether --with-procs was given.
+if test "${with_procs+set}" = set; then
+  withval=$with_procs; if test "$withval" = "yes"; then
+			NUM_PROCS=`expr $NUM_CPUS \* $PROC_MULTIPLY`
+		elif test ! "$withval" = "no";then
+			NUM_PROCS=$withval
+		fi
+else
+  NUM_PROCS=`expr $NUM_CPUS \* $PROC_MULTIPLY`
+
+fi
+
+	{ echo "$as_me:$LINENO: result: $NUM_PROCS" >&5
+echo "${ECHO_T}$NUM_PROCS" >&6; }
+
+
+{ echo "$as_me:$LINENO: checking glibc version" >&5
+echo $ECHO_N "checking glibc version... $ECHO_C" >&6; }
+	if test "${ac_cv_glibc_ver+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  dummy=if$$
+	cat <<_GLIBC_>$dummy.c
+#include <features.h>
+#include <stdio.h>
+#include <stdlib.h>
+int main(int argc, char **argv) { printf("libc6.%d",__GLIBC_MINOR__); exit(0); }
+_GLIBC_
+	${CC-cc} $dummy.c -o $dummy > /dev/null 2>&1
+	if test "$?" = 0; then
+		GLIBC_VER=`./$dummy`
+		{ echo "$as_me:$LINENO: result: $GLIBC_VER" >&5
+echo "${ECHO_T}$GLIBC_VER" >&6; }
+		ac_cv_glibc_ver=$GLIBC_VER
+	else
+		{ echo "$as_me:$LINENO: WARNING: cannot determine GNU C library minor version number" >&5
+echo "$as_me: WARNING: cannot determine GNU C library minor version number" >&2;}
+	fi
+	rm -f $dummy $dummy.c
+
+fi
+
+	GLIBC_VER="-$ac_cv_glibc_ver"
+
+
+{ echo "$as_me:$LINENO: checking libstdc++ version" >&5
+echo $ECHO_N "checking libstdc++ version... $ECHO_C" >&6; }
+	dummy=if$$
+	cat <<_LIBSTDCPP_>$dummy.cc
+#include <features.h>
+#include <stdio.h>
+#include <stdlib.h>
+int main(int argc, char **argv) { exit(0); }
+_LIBSTDCPP_
+	${CXX-c++} $dummy.cc -o $dummy > /dev/null 2>&1
+
+	if test "$?" = 0; then
+		soname=`objdump -p ./$dummy |grep NEEDED|grep libstd`
+                LIBSTDCPP_VER=`echo $soname | sed -e 's/.*NEEDED.*libstdc++\(-libc.*\(-.*\)\)\?.so.\(.*\)/\3\2/'`
+	fi
+	rm -f $dummy $dummy.cc
+
+	if test -z "$LIBSTDCPP_VER"; then
+		{ echo "$as_me:$LINENO: WARNING: cannot determine standard C++ library version number" >&5
+echo "$as_me: WARNING: cannot determine standard C++ library version number" >&2;}
+	else
+		{ echo "$as_me:$LINENO: result: $LIBSTDCPP_VER" >&5
+echo "${ECHO_T}$LIBSTDCPP_VER" >&6; }
+		LIBSTDCPP_VER="-$LIBSTDCPP_VER"
+	fi
+
+
+
+	{ echo "$as_me:$LINENO: checking if $CXX -MD works" >&5
+echo $ECHO_N "checking if $CXX -MD works... $ECHO_C" >&6; }
+	touch gcc3dep.cc
+	${CXX-c++} -MD -o gcc3dep_test.o -c gcc3dep.cc
+	rm -f gcc3dep.cc gcc3dep_test.o
+	if test -e gcc3dep.d; then
+		rm -f gcc3dep.d
+		GCC_MD=input
+		GCC3DEP=
+	elif test -e gcc3dep_test.d; then
+		rm -f gcc3dep_test.d
+		GCC_MD=output
+		GCC3DEP=yes
+	else
+		{ { echo "$as_me:$LINENO: error: no" >&5
+echo "$as_me: error: no" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	{ echo "$as_me:$LINENO: result: yes, for $GCC_MD" >&5
+echo "${ECHO_T}yes, for $GCC_MD" >&6; }
+
+
 
 ALL_LINGUAS="bg bs ca cs cy da de dz el en_GB es eu fi fr gl hu it ja ko ku nb nl nn pl pt_BR pt ro ru sk sl sv tl uk vi zn_CN zh_TW"
 { echo "$as_me:$LINENO: checking whether ${MAKE-make} sets \$(MAKE)" >&5
@@ -9860,6 +10141,13 @@ XMLTO!$XMLTO$ac_delim
 HAVE_DOT!$HAVE_DOT$ac_delim
 DOT!$DOT$ac_delim
 DOTDIR!$DOTDIR$ac_delim
+GETCONF!$GETCONF$ac_delim
+NUM_CPUS!$NUM_CPUS$ac_delim
+PROC_MULTIPLY!$PROC_MULTIPLY$ac_delim
+NUM_PROCS!$NUM_PROCS$ac_delim
+GLIBC_VER!$GLIBC_VER$ac_delim
+LIBSTDCPP_VER!$LIBSTDCPP_VER$ac_delim
+GCC3DEP!$GCC3DEP$ac_delim
 SET_MAKE!$SET_MAKE$ac_delim
 INSTALL_PROGRAM!$INSTALL_PROGRAM$ac_delim
 INSTALL_SCRIPT!$INSTALL_SCRIPT$ac_delim
@@ -9870,13 +10158,6 @@ MSGFMT!$MSGFMT$ac_delim
 GMSGFMT!$GMSGFMT$ac_delim
 MSGFMT_015!$MSGFMT_015$ac_delim
 GMSGFMT_015!$GMSGFMT_015$ac_delim
-XGETTEXT!$XGETTEXT$ac_delim
-XGETTEXT_015!$XGETTEXT_015$ac_delim
-MSGMERGE!$MSGMERGE$ac_delim
-INTL_MACOSX_LIBS!$INTL_MACOSX_LIBS$ac_delim
-LIBICONV!$LIBICONV$ac_delim
-LTLIBICONV!$LTLIBICONV$ac_delim
-INTLLIBS!$INTLLIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -9918,6 +10199,13 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+XGETTEXT!$XGETTEXT$ac_delim
+XGETTEXT_015!$XGETTEXT_015$ac_delim
+MSGMERGE!$MSGMERGE$ac_delim
+INTL_MACOSX_LIBS!$INTL_MACOSX_LIBS$ac_delim
+LIBICONV!$LIBICONV$ac_delim
+LTLIBICONV!$LTLIBICONV$ac_delim
+INTLLIBS!$INTLLIBS$ac_delim
 LIBINTL!$LIBINTL$ac_delim
 LTLIBINTL!$LTLIBINTL$ac_delim
 POSUB!$POSUB$ac_delim
@@ -9926,7 +10214,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 6; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 13; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
